import "./Experience.scss";
import Resume from "../../assets/files/Zisheng_Cai_resume.pdf";

const Experience = () => {
  return (
    <section id="Experience">
      <div className="container-fluid">
        <h1>XPeng Motors</h1>
        <div className="row">
          <h2 className="col-lg-6">Intern, Autonomous Driving Center</h2>
          <h2 className="col-lg-6" style={{ textAlign: "right" }}>
            12/2021 - 05/2022
          </h2>
        </div>
        <ul>
          <li>
            Processed and visualized about 20 million pieces of data to analyze
            the performances of the algorithm in over 10 different situations by
            Python.
          </li>
          <li>
            Leveraged algorithms, such as Dijkstra and A*, to help find the
            shortest way of autonomous parking.
          </li>
          <li>
            Discovered that the data generated by the new parking algorithm did
            not fit the key-value pairs like SQL, and applied NoSQL to store and
            analyze data, which reduced about 20% running time of data searching
          </li>
          <li>
            Collaborated with the testing department and driving center to
            access the new algorithm outcomes and negotiate the weakness of the
            new parking algorithm.
          </li>
        </ul>
        <h1>Fengyun IOT Technology Ltd</h1>
        <div className="row">
          <h2 className="col-lg-6">Data Analyst Intern</h2>
          <h2 className="col-lg-6" style={{ textAlign: "right" }}>
            07/2021 - 11/2021
          </h2>
        </div>
        <ul>
          <li>
            Collected routine data by SQL, with Python and R to clean, summarize
            and analyze data of chemical indicators, filtered abnormal data by
            statistical methods in SPSS to identify possible issues, and send
            daily data analysis reports
          </li>
          <li>
            Implemented clustering algorithms like K-means to classify water
            quality data from different sewage plants and summarized
            similarities and differences among those plants.
          </li>
          <li>
            Communicated with environmental engineers about the result of
            K-means and helped prioritize future tasks.
          </li>
        </ul>
        <br />

        <a className="btn btn-lg btn-outline-dark" href={Resume}>
            Download CV
        </a>
        
        {/* This code can view the resume online
        <form method="get" action={Resume}>
          <button type="submit" class="btn btn-lg btn-outline-dark">
            Download CV
          </button>
        </form> */}
      </div>
    </section>
  );
};

export default Experience;
